/* eslint-disable */
var demoArrTetris=[
    [
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        }
    ],
    [
        {
            "color":"#fffeff",
            "v":1
        },
        {
            "color":"#fffeff",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        }
    ],
    [
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        }
    ],
    [
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"#fffeff",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        }
    ],
    [
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#fffeff",
            "v":1
        },
        {
            "color":"#fffeff",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        }
    ],
    [
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#fffeff",
            "v":1
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        },
        {
            "color":"black",
            "v":0
        }
    ],
    [
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#2eb788",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"#ca4679",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        }
    ],
    [
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        }
    ],
    [
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        }
    ],
    [
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":1
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":0
        },
        {
            "color":"crimson",
            "v":1
        }
    ]
];

export default demoArrTetris;